title: Lee Ye Hoon
description: Imbeded-Engineer
site_title: '@abhn - Lee Ye Hoon'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: leeyehoon
blog_url: 
email: lyhh3442@naver.com
keybase_username: 
twitter_username: 
reddit_username: 

# absolute or relative
profile_picture: assets/images/img_profile.jpg

# Google Analytics ID
google_analytics: 